"""add unique constraint

Revision ID: 3d8592f4e499
Revises: a93aad4d6e45
Create Date: 2024-08-28 18:19:21.973209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d8592f4e499'
down_revision: Union[str, None] = 'a93aad4d6e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_cities_name', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_constraint('uq_cities_name', type_='unique')
    # ### end Alembic commands ###
